### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by crosswick** [gaudot/SlicerDentalSegmentator#34]
Hello, earlier this year in Slicer 5.71 I was able to segment the CBCT surgery demo. 

Now with 5.90 and the newest Segmentator, on the same system I get this error, could you help please?

`torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 7.38 GiB. GPU 0 has a total capacity of 4.00 GiB of which 0 bytes is free. Of the allocated memory 1.39 GiB is allocated by PyTorch, and 2.88 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)`

**Comment by Thibault-Pelletier** [comment]
Hi @crosswick,

This problem seems to be coming from insufficient CUDA memory on your system for the volume you are trying to run.
Between Slicer 5.71 and Slicer 5.9 the memory requirements for the Dental Segmentator haven't changed.

Although the results will be slower, you can fallback to CPU processing when encountering this problem.

For reference, for TotalSegmentator and other similar AI, a 24GB GPU is recommended to be able to process most medical volumes directly on the GPU.

Best,
Thibault

**Comment by crosswick** [comment]
Thank you - can I regress to a previous version of both Slicer and the Segmentator?

I'm positive the same system was working with the same data earlier.

**Comment by Thibault-Pelletier** [comment]
Sure, you can download older versions of 3D Slicer directly from the website : https://download.slicer.org/

For the extension, you will get the latest extension version when downloading it from the extension manager.
Otherwise, you will have to git pull the extension and checkout the version you like best.

**Comment by AntonOnyshch** [comment]
In my case it is not working on Ubuntu with rtx4070.

**3DSlicer error:** Failed to load the segmentation.
Something went wrong during the nnUNet processing.
Please check the logs for potential errors and contact the library maintainers.

**Log**: torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 7.38 GiB. GPU 0 has a total capacity of 11.59 GiB of which 6.63 GiB is free. Including non-PyTorch memory, this process has 4.53 GiB memory in use. Of the allocated memory 890.13 MiB is allocated by PyTorch, and 3.47 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)


Setting "PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True " into .bashrc and starting slicer from terminal or into .profile for desktop launch **leads to 3DSlicer crashes** immediately after i press "Apply" button for segmentations. 

For now i use CPU instead of CUDA and it works
